use std::cell::RefCell;
use std::rc::Rc;
use std::sync::atomic::Ordering;

use downcast::Downcast;

use wayland_commons::map::ObjectMap;
use wayland_commons::wire::Message;
use wayland_commons::MessageGroup;

use crate::{Filter, Interface, Resource};

mod clients;
mod display;
mod event_loop_glue;
mod globals;
mod resources;

pub(crate) use self::clients::ClientInner;
pub(crate) use self::display::DisplayInner;
pub(crate) use self::globals::GlobalInner;
pub(crate) use self::resources::ResourceInner;

/// A handle to the object map internal to the library state
///
/// This type is only used by code generated by `wayland-scanner`, and can not
/// be instantiated directly.
pub struct ResourceMap {
    map: Rc<RefCell<ObjectMap<self::resources::ObjectMeta>>>,
    client: ClientInner,
}

impl ResourceMap {
    fn make(map: Rc<RefCell<ObjectMap<self::resources::ObjectMeta>>>, client: ClientInner) -> ResourceMap {
        ResourceMap { map, client }
    }

    /// Returns the `Resource` corresponding to a given id
    pub fn get<I: Interface>(&mut self, id: u32) -> Option<Resource<I>> {
        ResourceInner::from_id(id, self.map.clone(), self.client.clone()).map(|object| {
            debug_assert!(I::NAME == "<anonymous>" || object.is_interface::<I>());
            Resource::wrap(object)
        })
    }

    /// Creates a `NewResource` for a given id
    pub fn get_new<I: Interface>(&mut self, id: u32) -> Option<Resource<I>> {
        debug_assert!(self
            .map
            .borrow_mut()
            .find(id)
            .map(|obj| obj.is_interface::<I>())
            .unwrap_or(true));
        ResourceInner::from_id(id, self.map.clone(), self.client.clone()).map(Resource::wrap)
    }
}

/*
 * Dispatching logic
 */
pub(crate) enum Dispatched {
    Yes,
    NoDispatch(Message, ResourceInner),
    BadMsg,
}

pub(crate) trait Dispatcher: Downcast {
    fn dispatch(&mut self, msg: Message, resource: ResourceInner, map: &mut ResourceMap) -> Dispatched;
}

mod dispatcher_impl {
    // this mod has for sole purpose to allow to silence these `dead_code` warnings...
    #![allow(dead_code)]
    use super::Dispatcher;
    impl_downcast!(Dispatcher);
}

pub(crate) struct ImplDispatcher<I: Interface + From<Resource<I>>, F: FnMut(I::Request, Resource<I>)> {
    _i: ::std::marker::PhantomData<&'static I>,
    implementation: F,
}

impl<I, F> Dispatcher for ImplDispatcher<I, F>
where
    I: Interface + From<Resource<I>>,
    F: FnMut(I::Request, Resource<I>) + 'static,
    I::Request: MessageGroup<Map = ResourceMap>,
{
    fn dispatch(&mut self, msg: Message, resource: ResourceInner, map: &mut ResourceMap) -> Dispatched {
        let opcode = msg.opcode as usize;
        if ::std::env::var_os("WAYLAND_DEBUG").is_some() {
            eprintln!(
                " <- {}@{}: {} {:?}",
                resource.object.interface, resource.id, resource.object.requests[opcode].name, msg.args
            );
        }
        let message = match I::Request::from_raw(msg, map) {
            Ok(msg) => msg,
            Err(_) => return Dispatched::BadMsg,
        };
        if message.since() > resource.version() {
            eprintln!(
                "Received an request {} requiring version >= {} while resource {}@{} is version {}.",
                resource.object.requests[opcode].name,
                message.since(),
                resource.object.interface,
                resource.id,
                resource.version()
            );
            return Dispatched::BadMsg;
        }
        if message.is_destructor() {
            resource.object.meta.alive.store(false, Ordering::Release);
            let mut kill = false;
            if let Some(ref mut data) = *resource.client.data.borrow_mut() {
                data.schedule_destructor(resource.clone());
                kill = data.delete_id(resource.id).is_err();
            }
            if kill {
                resource.client.kill();
            }
            (self.implementation)(message, Resource::<I>::wrap(resource.clone()).into());
        } else {
            (self.implementation)(message, Resource::<I>::wrap(resource).into());
        }
        Dispatched::Yes
    }
}

pub(crate) fn make_dispatcher<I, E>(filter: Filter<E>) -> Rc<RefCell<dyn Dispatcher>>
where
    I: Interface + AsRef<Resource<I>> + From<Resource<I>>,
    E: From<(Resource<I>, I::Request)> + 'static,
    I::Request: MessageGroup<Map = ResourceMap>,
{
    Rc::new(RefCell::new(ImplDispatcher {
        _i: ::std::marker::PhantomData,
        implementation: move |evt, res| filter.send((res, evt).into()),
    }))
}

pub(crate) fn default_dispatcher() -> Rc<RefCell<dyn Dispatcher>> {
    struct DefaultDisp;
    impl Dispatcher for DefaultDisp {
        fn dispatch(&mut self, msg: Message, resource: ResourceInner, _map: &mut ResourceMap) -> Dispatched {
            Dispatched::NoDispatch(msg, resource)
        }
    }

    Rc::new(RefCell::new(DefaultDisp))
}

pub(crate) fn make_destructor<I, E>(filter: Filter<E>) -> Rc<RefCell<dyn FnMut(ResourceInner)>>
where
    I: Interface + AsRef<Resource<I>> + From<Resource<I>>,
    E: From<Resource<I>> + 'static,
{
    Rc::new(RefCell::new(move |res| {
        filter.send(Resource::<I>::wrap(res).into())
    }))
}
