task:
  matrix:
    - name: FreeBSD 11.3
      freebsd_instance:
        image_family: freebsd-11-3-snap
    - name: FreeBSD 12.1
      freebsd_instance:
        image_family: freebsd-12-1-snap
    - name: FreeBSD 13.0
      freebsd_instance:
        image_family: freebsd-13-0-snap
 # Install Rust
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain stable
    - pkg update -f
    - pkg install -y git wayland
    - git submodule update --init --recursive
  test_script:
    - . $HOME/.cargo/env
    - mkdir -p $HOME/sockets
    - export XDG_RUNTIME_DIR="$HOME/sockets"
    - cargo test --features "both_native" --all
