use crate::{Interface, Resource};

mod client;
mod display;
mod globals;
mod resource;

pub(crate) use self::client::ClientInner;
pub(crate) use self::display::DisplayInner;
pub(crate) use self::globals::GlobalInner;
pub(crate) use self::resource::ResourceInner;

/// A handle to the object map internal to the library state
///
/// This type is only used by code generated by `wayland-scanner`, and can not
/// be instantiated directly.
pub enum ResourceMap {}

impl ResourceMap {
    /// Returns the `Resource` corresponding to a given id
    pub fn get<I: Interface>(&mut self, _id: u32) -> Option<Resource<I>> {
        match *self {}
    }
    /// Creates a `NewResource` for a given id
    pub fn get_new<I: Interface>(&mut self, _id: u32) -> Option<Resource<I>> {
        match *self {}
    }
}
